name: HCX Platform - Tag Build

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Maven Build
        run: |
          mvn clean install
          cd hcx-scheduler-jobs
          mvn clean install
          cd hcx-pipeline-jobs
          mvn clean install

      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set the Image TAG
        run: echo "IMAGE_TAG=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build and push Docker image for API-Gateway
        uses: docker/build-push-action@v3
        with:
          context: ./api-gateway
          push: true
          tags: swasth2021/api-gateway:${{ env.IMAGE_TAG }}_${{ github.run_number }}
          labels: api-gateway image

      - name: Build and push Docker image for HCX-APIs
        uses: docker/build-push-action@v3
        with:
          context: ./hcx-apis
          push: true
          tags: swasth2021/hcx-api:${{ env.IMAGE_TAG }}_${{ github.run_number }}
          labels: hcx-api image

      - name: Build and push Docker image for HCX Scheduler Job
        uses: docker/build-push-action@v3
        with:
          context: ./hcx-scheduler-jobs
          push: true
          tags: swasth2021/hcx-scheduler-jobs:${{ env.IMAGE_TAG }}_${{ github.run_number }}
          labels: hcx-scheduler-jobs image

      - name: Build and push Docker image for hcx-pipeline-jobs
        uses: docker/build-push-action@v3
        with:
          context: ./hcx-pipeline-jobs/jobs-distribution
          push: true
          tags: swasth2021/hcx-pipeline-jobs:${{ env.IMAGE_TAG }}_${{ github.run_number }}
          labels: hcx-pipeline-jobs image